name: Release Drafter

on: 
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: toolmantim/release-drafter@v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
